config/routes.rb
Apollo::Application.routes.draw do
  

  resources :tenants

  resources :properties

  match '/about', :to => 'pages#about'

  match '/contact', :to => 'pages#contact'
  
  match '/tour', :to => 'pages#tour'
  
  match '/new', :to => 'properties#new'
  
  match '/index', :to => 'properties#index' 
  
  match '/destroy', :to => 'properties#destroy'

  root :to => 'pages#home'

end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :tenants
  validates :address1, :address2, :status, :number_of_occupants, :price, :presence => true
  validates :price, :numericality => { :greater_than_or_equal_to => 0.01 }
  validates :address1, :uniqueness => true
  # validates :image_url, :format => {
  #  :with    => %r{\.(gif|jpg|png)$}i,
  #  :message => 'must be a URL for GIF, JPG or PNG image.'
  # }
  
  COUNTRY = [ "Ireland", "United Kingdom" ]
  
  STATUS = [ "Vacant", "Occupied" ]
  
  PAYMENT_TYPE = [ "Direct Debit", "Standing Order", "Cheque", "Cash" ]
  
  PAYMENT_FREQUENCY = [ "Weekly", "Bi-monthly", "Monthly", "Quaterly" ]
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
  belongs_to :property
  def validate
    if number_of_tenants > property.number_of_occupants
      errors.add_to_base("You have exceed the number of tenants for this property")
    end
    if property.tenants.size >= property.number_of_occupants
      errors.add_to_base("This property has reached its maximum occupnacy")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def about
    @title = "About Us"
  end

  def contact
    @title = "Contact Us"
  end
  
  def tour
    @title = "Tour"
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  
  layout "properties"
  # GET /properties
  # GET /properties.xml
  def index
    @title = "Control Panel"
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.xml
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.xml
  def new
    @property = Property.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.xml
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to(@property, :notice => 'Property was successfully created.') }
        format.xml  { render :xml => @property, :status => :created, :location => @property }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @property.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.xml
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to(@property, :notice => 'Property was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @property.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.xml
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to(properties_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  
  layout "properties"
  # GET /tenants
  # GET /tenants.xml
  def index
    @tenants = Tenant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tenants }
    end
  end

  # GET /tenants/1
  # GET /tenants/1.xml
  def show
    @tenant = Tenant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tenant }
    end
  end

  # GET /tenants/new
  # GET /tenants/new.xml
  def new
    @tenant = Tenant.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tenant }
    end
  end

  # GET /tenants/1/edit
  def edit
    @tenant = Tenant.find(params[:id])
  end

  # POST /tenants
  # POST /tenants.xml
  def create
    @tenant = Tenant.new(params[:tenant])

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to(@tenant, :notice => 'Tenant was successfully created.') }
        format.xml  { render :xml => @tenant, :status => :created, :location => @tenant }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tenant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tenants/1
  # PUT /tenants/1.xml
  def update
    @tenant = Tenant.find(params[:id])

    respond_to do |format|
      if @tenant.update_attributes(params[:tenant])
        format.html { redirect_to(@tenant, :notice => 'Tenant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tenant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1
  # DELETE /tenants/1.xml
  def destroy
    @tenant = Tenant.find(params[:id])
    @tenant.destroy

    respond_to do |format|
      format.html { redirect_to(tenants_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="container">
		<div class="span-24 content">
			<p><%= link_to "About Us", about_path %> | <%= link_to "Contact Us", contact_path %> | <%= link_to "Terms & Conditions", '#' %> | <%= link_to "Site Map", '#' %> | <%= link_to "Privacy Policy", '#' %> | <%= link_to "F.A.Q", '#' %> | <%= link_to "Help", '#' %></p>
		</div>
	</div>
<div>

app/views/layouts/_header.html.erb
<div class="header">
	<div class="container">
		<h1><%= link_to "The Rent Book", root_path %><h1>
		<div id="login"><a href="signup.html" title="Sign Up">Sign Up</a> | <a href="login.html" title="Log In">Log In</a></div>
	<div id="nav">
		<ul>
			<li class="first current"><%= link_to "home", root_path %></li>
			<li><%= link_to "take the tour", tour_path %></li>
			<li><%= link_to "about us", about_path %></li>
			<li><%= link_to "contact us", contact_path %></li>
		</ul>
	</div>
	</div>
</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'grid', :type => 'text/css', :media => 'all' %>
<%= stylesheet_link_tag 'print', :type => 'text/css', :media => 'all' %>
<%= stylesheet_link_tag 'screen', :type => 'text/css', :media => 'all' %>
<%= stylesheet_link_tag 'style.css', :id => 'defaultStyle', :type => 'text/css',  :media => 'all' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Rent Book | <%= @title %></title>
 
  <%= render 'layouts/stylesheets' %>
  <%= csrf_meta_tag %>
  <%= javascript_include_tag :all %>

<script type="text/javascript">
$(document).ready(function(){
	$('HTML').addClass('JS');

	$("#tabs").tabs();

	//used to give all tabs the same height
	var maxHeight=0;
	$("#tabs div").each(function(){
		var myDiv=$(this);
		var isHidden=false;
		if(myDiv.hasClass("ui-tabs-hide")){
			isHidden=true;
			myDiv.removeClass("ui-tabs-hide");
		}
		if((myHeight=myDiv.height())>maxHeight){
			maxHeight=myHeight;	
		}else{
			myDiv.height(maxHeight);	
		}
		if(isHidden){
			myDiv.addClass("ui-tabs-hide");
		}
	});

	$("#slide").cycle({
		fx: 		'scrollDown',
		timeout: 	'4000'
	});
});
</script>
  
</head>
<body id="home">
	
<!-- ****************************** header ****************** -->

<%= render 'layouts/header' %>
	
<!-- ****************************** content ***************** -->

<%= yield %>
	
<!-- ###################### footer ##################### -->

<%= render 'layouts/footer' %>				


</body>
</html>

app/views/layouts/properties.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><%= @title %></title>
<%= stylesheet_link_tag 'layout', :type => 'text/css', :media => 'all' %>
<%= stylesheet_link_tag 'wysiwyg', :type => 'text/css', :media => 'all' %>
<%= stylesheet_link_tag 'themes/styles', :type => 'text/css', :media => 'all' %>

<%= javascript_include_tag :all %>

<%= csrf_meta_tag %>
</head>

<body id="homepage">
	<div id="header">
    	<%= link_to image_tag("../admin_images/cp_logo.png", :alt => "Control Panel"), index_path %>
    	<div id="searcharea">
            
            <input type="text" class="searchbox" value="Jump to property or tenant..." onclick="if (this.value =='Jump to property or tenant...'){this.value=''}"/>
            <input type="submit" value="Search" class="searchbtn" />
        </div>
    </div>
        
    <!-- Top Breadcrumb Start -->
    <div id="breadcrumb">
    	<ul>	
        	<li><%= image_tag("../admin_images/icons/icon_breadcrumb.png", :alt => "Path") %></li>
        	<li><strong>Location:</strong></li>
            <li><a href="#" title="">Sub Section</a></li>
            <li>/</li>
            <li class="current">Control Panel</li>
        </ul>
    </div>
    <!-- Top Breadcrumb End -->
     
    <!-- Right Side/Main Content Start -->
    <div id="rightside">
    
        
        
     <%= yield %>

       
        <div id="footer">
        	&copy; Copyright 2011 The Rent Book
        </div> 
          
    </div>
    <!-- Right Side/Main Content End -->
    
        <!-- Left Dark Bar Start -->
    <div id="leftside">
    	<div class="user">
        	<%= image_tag("../admin_images/avatar.png", :width => "44", :height => "44", :class => "hovering",  :alt => "Avatar") %>
            <p>Logged in as:</p>
            <p class="username">Administrator</p>
            <p class="userbtn"><a href="#" title="">Profile</a></p>
            <p class="userbtn"><a href="#" title="">Log out</a></p>
        </div>
        <div class="notifications">
        	<p class="notifycount"><a href="" title="" class="notifypop">10</a></p>
            <p><a href="" title="" class="notifypop">New Notifications</a></p>
            <p class="smltxt">(Click to open notifications)</p>
        </div>
        
        <ul id="nav">
        	<li>
                <ul class="navigation">
                    <li class="heading selected">Current Section</li>
                    <li><%= link_to "Create a new property", new_property_path %></li>
                    <li><%= link_to "New Tenant", new_tenant_path %></li>
                    <li><a href="#" title="">Section link here</a></li>
                </ul>
            </li>
            <li>
                <a class="collapsed heading">Section Heading</a>
                 <ul class="navigation">
                    <li><a href="#" title="">Section link here</a></li>
                    <li><a href="#" title="">Section link here</a></li>
                    <li><a href="#" title="">Section link here</a></li>
                </ul>
            </li>
            <li><a class="expanded heading">Section Heading</a>
                <ul class="navigation">
                    <li><a href="#" title="" class="likelogin">Section link here</a></li>
                    <li><a href="#" title="">Section link here</a></li>
                    <li><a href="#" title="">Section link here</a></li>
                </ul>
            </li>            
        </ul>
    </div>
    <!-- Left Dark Bar End --> 
    
    <!-- Notifications Box/Pop-Up Start --> 
    <div id="notificationsbox">
        <h4>Notifications</h4>
        <ul>
            <li>
            	<a href="#" title=""><img src="../admin_images/icons/icon_square_close.png" alt="Close" class="closenot" /></a>
            	<h5><a href="#" title="">New member registration</a></h5>
                <p>Admin eve joined on 18.12.2010</p>
            </li>
            <li>
            	<a href="#" title=""><img src="../admin_images/icons/icon_square_close.png" alt="Close" class="closenot" /></a>
            	<h5><a href="#" title="">New member registration</a></h5>
                <p>Jackson Michael joined on 16.12.2010</p>
            </li>
            <li>
            	<a href="#" title=""><img src="../admin_images/icons/icon_square_close.png" alt="Close" class="closenot" /></a>
                <h5><a href="#" title="">New blog post created</a></h5>
                <p>New post created on 15.12.2010</p>
            </li>
            <li>
            	<a href="#" title=""><img src="../admin_images/icons/icon_square_close.png" alt="Close" class="closenot" /></a>
            	<h5><a href="#" title="">New group created</a></h5>
                <p>“Web Design” group created on 12.12.2010</p>
            </li>
            <li>
            	<a href="#" title=""><img src="../admin_images/icons/icon_square_close.png" alt="Close" class="closenot" /></a>
            	<h5><a href="#" title="">1 new private message</a></h5>
                <p>New message from Joe sent on 21.11.2010</p>
            </li>
            <li>
            	<a href="#" title=""><img src="../admin_images/icons/icon_square_close.png" alt="Close" class="closenot" /></a>
            	<h5><a href="#" title="">New member registration</a></h5>
                <p>Graham joined on 20.11.2010</p>
            </li>
        </ul>
        <p class="loadmore"><a href="#" title="">Load more notifications</a></p>
    </div>
    <!-- Notifications Box/Pop-Up End --> 
    
  
    
    <!--[if IE 6]>
    <script type='text/javascript' src='scripts/png_fix.js'></script>
    <script type='text/javascript'>
      DD_belatedPNG.fix('img, .notifycount, .selected');
    </script>
    <![endif]--> 
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>This is the about page for the web app The Rent Book</p>

app/views/pages/contact.html.erb
<div id="page">
  <div class="wrapper">
    <div class="container">
<div id="content-zone" class="prepend-3 span-18 append-3 last">
<h2>Contact Us</h2>
<div class="outer"><div class="inner"><div class="sub acenter">

<div class="video"><embed src=""  type="application/x-shockwave-flash" width="600" height="470" allowscriptaccess="always" allowfullscreen="true"></embed></div>

<hr/>
<div class="clearfix"><a class="button fright" href="signup.html" title="Sign Up">Sign up</a>
<p class="aleft">Lorum Ipsum.</p></div>
</div></div></div>
</div>
      
    </div>
  </div>
</div>

app/views/pages/tour.html.erb
<div id="page">
  <div class="wrapper">
    <div class="container">
<div id="content-zone" class="prepend-3 span-18 append-3 last">
<h2>Take the tour</h2>
<div class="outer"><div class="inner"><div class="sub acenter">

<div class="video"><embed src=""  type="application/x-shockwave-flash" width="600" height="470" allowscriptaccess="always" allowfullscreen="true"></embed></div>

<hr/>
<div class="clearfix"><a class="button fright" href="signup.html" title="Sign Up">Sign up</a>
<p class="aleft">A random but cool video from blip.tv. </p></div>
</div></div></div>
</div>
      
    </div>
  </div>
</div>

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	
      <div class="contentbox">
      	<table width="100%">
          	<thead>
              		<tr>
                  		<th>Address</th>
						<th>Town</th>
						<th>City</th>
						<th>Postcode</th>
						<th>Country</th>												
					</tr>
            </thead>
            <tbody>
              		<tr>
                  		<td><%= f.text_field :address1 %></td>
                      	<td><%= f.text_field :address2 %></td>
						<td><%= f.text_field :address3 %></td>
						<td><%= f.text_field :address4 %></td>
						<td><%= f.select :country, Property::COUNTRY, :prompt => 'Select a country' %>
					</tr>
			</tbody>
		</table>
			
		<table>
			<thead>
              		<tr>
						<th>Maximum Occupancy</th>
                  		<th>Currently</th>
						<th>Rent</th>
						<th>Rent Frequency</th>
						<th>Payment Type</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						
																		
					</tr>
            </thead>
			<tbody>
              		<tr>
						<td><%= f.text_field :number_of_occupants %></td>
                  		<td><%= f.select :status, Property::STATUS, :prompt => 'Select status' %></td>
						<td><%= number_to_currency (f.text_field :price) %></td>
                      	<td><%= f.select :payment_frequency, Property::PAYMENT_FREQUENCY, :prompt => 'Select frequency' %></td>
						<td><%= f.select :payment_type, Property::PAYMENT_TYPE, :prompt => 'Select payment method' %></td>
					</tr>
			</tbody>
		</table>

<br />

		<div class="actions">
		    <%= f.submit %>
		  </div>
          
          <div style="clear: both;"></div>
      </div>
      
  </div>
<% end %>

app/views/properties/_new_tenant.html.erb
<%= form_for(tenant) do |f| %>
  <% if tenant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
      <% tenant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<h2>Nw Tenant</h2>

  <div class="field">
    <%= f.hidden_field :property_id %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br />
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br />
    <%= f.text_field :contact_number %>
  </div>
  <div class="field">
    <%= f.label :move_in_date %><br />
    <%= f.date_select :move_in_date %>
  </div>
  <div class="field">
    <%= f.label :move_out_date %><br />
    <%= f.date_select :move_out_date %>
  </div>
  <div class="field">
    <%= f.label :number_of_tenants %><br />
    <%= f.text_field :number_of_tenants %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/_tenants_list.html.erb
<br />
<div class="contentcontainer">
	<div class="headings altheading">
    	<h2>All Tenants</h2><br />
	</div>
<div class="contentbox">
	<table width="100%">
    	<thead>
        	<tr>
            	<th>First Name</th>
			    <th>Family Name</th>
			    <th>Email address</th>
			    <th>Contact number</th>
				<th>Move in date</th>
			    <th>Move out date</th>
				<th>Actions</th>
            </tr>
        </thead>
        <tbody>
        	<tr>
				<% tenants.each do |tenant| %>
				  <tr>
				    <td><%= tenant.first_name %></td>
				    <td><%= tenant.last_name %></td>
				    <td><%= tenant.email_address %></td>
					<td><%= tenant.contact_number %></td>
					<td><%= tenant.move_in_date %></td>
					<td><%= tenant.move_out_date %></td>
				    <td><%= link_to 'Show', tenant %> | <%= link_to 'Edit', edit_tenant_path(tenant) %> |  <%= link_to 'Destroy', tenant, :confirm => 'Are you sure?', :method => :delete %></td>
				  </tr>
				<% end %>
        </tbody>
    </table>
  <!-- <div class="extrabottom">
        <div class="bulkactions"> 
        	
            	<%= link_to 'New Property', new_property_path %>
        </div>
    </div>
    <div style="clear: both;"></div> -->
    

</div>

app/views/properties/edit.html.erb
<div class="contentcontainer">
  <div class="headings altheading">
      <h2>Editing <%= @property.address1 %></h2>
  </div>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<!-- Alternative Content Box Start -->
     <div class="contentcontainer">
        <div class="headings altheading">
            <h2>All Properties</h2><br />
        </div>
        <div class="contentbox">
        	<table width="100%">
            	<thead>
                	<tr>
                    	<th>Address</th>
					    <th>Currently</th>
					    <th>Start date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                	<tr>
						<% @properties.each do |property| %>
						  <tr>
						    <td><%= property.address1 %></td>
						    <td><%= property.status %></td>
						    <td><%= property.start_date %></td>
						    <td><%= link_to 'Show', property %> | <%= link_to 'Edit', edit_property_path(property) %> |  <%= link_to 'Destroy', property, :confirm => 'Are you sure?', :method => :delete %></td>
						  </tr>
						<% end %>
                </tbody>
            </table>
           <!-- <div class="extrabottom">
            <ul>
                	<li><%= image_tag("../admin_images/icons/icon_edit.png") %> Edit</li>
                    <li><%= image_tag("../admin_images/icons/icon_approve.png") %> Approve</li>
                    <li><%= image_tag("../admin_images/icons/icon_unapprove.png") %> Unapprove</li>
                    <li><%= image_tag("../admin_images/icons/icon_delete.png") %> Remove</li>
                </ul>
                <div class="bulkactions"> 
                	
                    	 <%= link_to 'New Property', new_property_path %> 
                </div>
            </div> -->
            
            <div style="clear: both;"></div>
        </div>
    </div>
<%= render :partial => "tenants_list", :locals => { :tenants => Tenant.find(:all) } %>

</div>
    <!-- Alternative Content Box End -->




<br />

app/views/properties/new.html.erb
<div class="contentcontainer">
  <div class="headings altheading">
      <h2>New Property</h2>
  </div>

<%= render 'form' %>





<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="status success"><%= notice %></p>

   <!-- Alternative Content Box Start -->
     <div class="contentcontainer">
        <div class="headings altheading">
            <h2>Displaying <%= @property.address1 %></h2>
        </div>
        <div class="contentbox">
        	<table width="100%">
            	<thead>
                	<tr>
                    	<th>Address</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>												
					</tr>
                </thead>
                <tbody>
                	<tr>
                    	<td><%= @property.address1 %></td>
                        <td><%= @property.address2 %></td>
						<td><%= @property.address3 %></td>
						<td><%= @property.address4 %></td>
				</tbody>

<br />

				<thead>
                	<tr>
                    	<th>Status</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>Number of Occupants</th>
						<th></th>												
					</tr>
                </thead>

				<tbody>
                	<tr>
                    	<td><%= @property.status %></td>
                        <td><%= @property.start_date %></td>
						<td><%= @property.end_date %></td>
						<td><%= @property.number_of_occupants %></td>
				</tbody>

				<thead>
                	<tr>
                    	<th>Payment Type</th>
						<th>Property ID</th>
						<th>Monthly Rent</th>
						<th></th>
						<th></th>												
					</tr>
                </thead>

				<tbody>
                	<tr>
                    	<td><%= @property.payment_type %></td>
                        <td><%= @property.property_id %></td>
						<td><%= number_to_currency(@property.price) %></td>
				</tbody>
				
            </table>

			<div class="bulkactions"> 
            	
                	<%= link_to 'Edit this property', edit_property_path(@property) %> | <%= link_to 'Return to property listing', properties_path %>
            </div>
            
            <div style="clear: both;"></div>
        </div>
</div>

		<%= render :partial => "tenants_list", :locals => { :tenants => @property.tenants } %>

		<%= render :partial => "new_tenant", :locals => { :tenant => Tenant.new(:property_id => @property.id) } %>
        
    </div>


  

app/views/tenants/edit.html.erb
<h1>Editing tenant</h1>

<%= render 'form' %>

<%= link_to 'Show', @tenant %> |
<%= link_to 'Back', tenants_path %>

app/views/tenants/index.html.erb
<h1>Listing tenants</h1>

<table>
  <tr>
    <th><%= property.each do |property| %></th>
    <th>First name</th>
    <th>Last name</th>
    <th>Email address</th>
    <th>Contact number</th>
    <th>Move in date</th>
    <th>Move out date</th>
    <th>Number of tenants</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% end %>

<% @tenants.each do |tenant| %>
  <tr>
    <td><%= tenant.property_id %></td>
    <td><%= tenant.first_name %></td>
    <td><%= tenant.last_name %></td>
    <td><%= tenant.email_address %></td>
    <td><%= tenant.contact_number %></td>
    <td><%= tenant.move_in_date %></td>
    <td><%= tenant.move_out_date %></td>
    <td><%= tenant.number_of_tenants %></td>
    <td><%= link_to 'Show', tenant %></td>
    <td><%= link_to 'Edit', edit_tenant_path(tenant) %></td>
    <td><%= link_to 'Destroy', tenant, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/tenants/new.html.erb
<%= render 'form' %>

app/views/tenants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Property:</b>
  <%= @tenant.property_id %>
</p>

<p>
  <b>First name:</b>
  <%= @tenant.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @tenant.last_name %>
</p>

<p>
  <b>Email address:</b>
  <%= @tenant.email_address %>
</p>

<p>
  <b>Contact number:</b>
  <%= @tenant.contact_number %>
</p>

<p>
  <b>Move in date:</b>
  <%= @tenant.move_in_date %>
</p>

<p>
  <b>Move out date:</b>
  <%= @tenant.move_out_date %>
</p>

<p>
  <b>Number of tenants:</b>
  <%= @tenant.number_of_tenants %>
</p>


<%= link_to 'Edit', edit_tenant_path(@tenant) %> |
<%= link_to 'Back', tenants_path %>